### PR TITLE
iris v1

### PR DESCRIPTION
**Pull request by irisxue**
added dataset and diffusion fine tune files. please code review

### CODE REVIEW

**Comment by AudreyAcken** [comment]
are you checkpointing the finetuned model/saving it somewhere? that might be useful for future training

**Comment by AudreyAcken** [comment]
good job figuring out the textdiffuser pipeline!!

**Comment by irisxue** [comment]
> in the example img displayed it seems the book is slighly skewed, i'm wondering more image preprocessing would be helpful here to make sure the images are only of the book covers

yeah, i was thinking that too. I used this dataset because it already has captions. Most of the datasets with better images dont have captions. in the future we can probably do some web scraping to improve the model.

**Comment by Larrychen1133** [comment]
Nice job Iris! Great job trying a lot of different experiments and models

**Pull request merged**
